language: java
jdk:
  - openjdk11
env:
  global:
    - secure: "gQQ7yJ/PZGPXWqHgfZYtioHqerny2ExrxCNimgyBrTAtTSGbSBpum8jORhB56H7xzJvbZk4x6V6LwSCj2gISIQ6TBprO7SohMP2xKPtd83ADkjh60aPFwGcJoBN4R3dvGlaq8BRceUbVx2oVA8Mr0XYCPKc7tQQ7y/FTTzZK/jXo32tNfO1v6RQWKoolYZdI9mvD8pNgiHTLHOgQIwGRD7UUDEI0ROsCLLMnD/1MLEjCjL/JBHrgNf6TEcVvQy19sNghrcdy7cfJ4tLidD8q3RMFHIRhYH+lzDlYTIFXEeo1rdvXmT0lQGeQA1kDOyutvFx6Q/Tq0Cw/+UqwekovWDaD5W5Vn45KVay1cWEv7SOzqSX59QBY6y43sDH6Opd3BwNzS03qtAiaV15hRxn7/eAlWjWLr0mZYIPc6FJXUUOylfckGLu8HYb9DfsjR90bPbuHUS2pztlBNbLppF+wGigkpSqIh1A03bjo1rXTtOeR4Arw9kOau0svoofToXCGL4k/7ID6KIhDgnCLaMNEApFAmZzjkzSW3xH/KNdMtcDDajjFDcDKqCLFBiDiQbDSxyRCc+Gyam+UBjM8At57ZqKdwiUCzo7UbsJ47ORCWZ6+y4RmJDl9z2UtMRU28a0tgvgigSJyeDXAqI0s/6+Ryhisj/D/f/uPsr6WlpZCN+M="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "wultra/powerauth-crypto"
      description: Build submitted via Travis CI
    notification_email: roman.strobl@wultra.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan